apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: webapps  # Target namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io  # API group for the Role
  kind: Role                           # Reference to a Role (not ClusterRole)
  name: app-role                       # Name of the Role being bound
subjects:
  - kind: ServiceAccount              # Subject type
    name: jenkins                     # ServiceAccount name
    namespace: webapps               # Namespace of the ServiceAccount
